# Generated by Django 3.2 on 2022-12-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ufname', models.CharField(max_length=89)),
                ('ulname', models.CharField(max_length=88)),
                ('uaddress', models.CharField(max_length=540)),
                ('uphone', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default=0, max_length=80)),
                ('dfname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('address', models.CharField(max_length=540)),
                ('dcontact', models.CharField(max_length=120)),
                ('lno', models.CharField(max_length=120)),
                ('vno', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=90)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('pday', models.CharField(max_length=120)),
                ('phours', models.CharField(max_length=120)),
                ('pmonth', models.CharField(max_length=120)),
                ('pass1', models.CharField(max_length=90)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('fname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90)),
                ('pass1', models.CharField(max_length=90)),
                ('pass2', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inter_city.city')),
            ],
        ),
    ]
