# Generated by Django 3.2 on 2022-12-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
