# Generated by Django 3.2 on 2022-12-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_city', '0002_auto_20221230_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
