# Generated by Django 3.2 on 2023-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inter_city', '0003_auto_20221230_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='priceSelect',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='weightSelect',
            field=models.CharField(default=0, max_length=12, null='True'),
            preserve_default='True',
        ),
    ]
